### ISSUE TITLE
Reaper Downtime on Deploying Upgrade

### ISSUE THREAD

**Issue by ManApart** [smartcitiesdata/reaper#100]
Twice now Reaper has stopped reaping when the pods are rolled and a new version is deployed, causing production downtime. 

Reaper shows no error logs but stops adding messages to Kafka, despite the supervisor still running for a streaming dataset.

**Comment by bbrewer-papa-x** [comment]
Just messing around but this would be a readiness probe to try -

```
readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /app/bin/reaper rpc 'Horde.Cluster.members(Reaper.Horde.Supervisor) |> elem(1) |> Enum.any?(fn {_k, {s, p}} -> Process.whereis(Reaper.Horde.Supervisor) == p.pid and s == :alive end)' | grep -x true
```
